version: "3"
services:
  directus:
    image: directus/directus:10.10.4
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "some-key"
      SECRET: "some-secret"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:5173"
      ADMIN_EMAIL: "reinhart.logronio@msugensan.edu.ph"
      ADMIN_PASSWORD: "0ri0nMC10!"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"